WebTest/Controllers/FactoriesController.cs
using Microsoft.AspNetCore.Mvc;
using DataAccess.Models;
using WebTest.VWModels.Factory;
using Microsoft.EntityFrameworkCore;
namespace WebTest.Controllers
{
    public class FactoriesController : BaseController
    {
        public FactoriesController(PharmacyContext context) : base(context)
        {
        }
        override
        public async Task<IActionResult> Index()
        {
            return _context.Factories != null ?
                View(await _context.Factories.ToListAsync()) :
                Problem("Entity set 'PharmacyContext.Factories'  is null.");
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] CreateFactoryRequest factory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(new Factory()
                {
                    Name = factory.Name,
                });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(factory);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var factory = await _context.Factories
                            .FirstOrDefaultAsync(f => f.Id == id);
            if (factory is null)
            {
                return NotFound();
            }
            var filteredMedicines = _context.Medicines
                                    .Where(i => i.FactoryId == id)
                                    .Include(e => e.Category)
                                    .Include(e => e.ActiveSubstance)
                                    .ToList();

            var medicines = new VWModels.Factory.ShowMedicinesResponse();

            medicines.FactoryId = (int)id;
            medicines.Name = factory.Name;
            medicines.Medicines = filteredMedicines
                                    .Where(i => i.FactoryId == id)
                                    .Select(i => new MedicineInfo()
                                    {
                                        Id = i.Id,
                                        Name = i.Name,
                                        TradeName = i.TradeName,
                                        InStock = i.InStock,
                                        ActiveSubstance = i.ActiveSubstance.Name,
                                        Category = i.Category.Name,
                                        Dose = i.Dose,

                                    }).ToList();

            ViewBag.Medicines = medicines;
            return View(medicines);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var factory = await _context.Factories
                            .FirstOrDefaultAsync(f => f.Id == id);
            if (factory is null)
            {
                return NotFound();
            }

            return View(factory);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            if (_context.Factories is null)
            {
                return Problem("Entity set 'PharmacyContext.Factories  is null.");
            }
            var factory = await _context.Factories.FindAsync(id);
            if (factory is not null)
            {
                _context.Factories.Remove(factory);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var factory = await _context.Factories.FindAsync(id);
            if (factory is null)
            {
                return NotFound();
            }
            var factoryModel = new EditFactoryRequest()
            {
                Name = factory.Name,
            };

            return View(factoryModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, [Bind("Name")] EditFactoryRequest factory)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(new Factory()
                    {
                        Id = id,
                        Name = factory.Name,
                    });
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                    throw;

                }
                return RedirectToAction(nameof(Index));
            }
            return View(factory);
        }
    }
}

WebTest/Controllers/MedicinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DataAccess.Models;
using WebTest.VWModels.MedicineIngredient;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebTest.VWModels;

namespace WebTest.Controllers
{
    public class MedicinesController : BaseController
    {
        public MedicinesController(PharmacyContext context) : base(context)
        {
        }
        override
        public async Task<IActionResult> Index()
        {
            if(_context.Medicines is null)
                return Problem("Entity set 'PharmacyContext.Categories'  is null.");
            var medicines = await _context.Medicines
                            .Include(e => e.Factory)
                            .Include(e => e.Category)
                            .Include(e => e.ActiveSubstance)
                            .ToListAsync();
            return View(medicines);
        }
        public IActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(_context.Categories, "Id", "Name");
            ViewBag.ActiveSubstanceId = new SelectList(_context.Ingredients, "Id", "Name");
            ViewBag.FactoryId = new SelectList(_context.Factories, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, Description, CategoryId, Dose, ActiveSubstanceId, InStock, FactoryId, TradeName")] CreateMedicineRequest medicine)
        {
            if (ModelState.IsValid)
            {
                var newMedicine = new Medicine()
                {
                    Name = medicine.Name,
                    Description = medicine.Description,
                    CategoryId = medicine.CategoryId,
                    Dose = medicine.Dose,
                    ActiveSubstanceId = medicine.ActiveSubstanceId,
                    InStock = medicine.InStock,
                    FactoryId = medicine.FactoryId,
                    TradeName = medicine.TradeName,
                };
                _context.Add(newMedicine);
                await _context.SaveChangesAsync();
                _context.Add(new MedicineIngredient()
                {
                    MedicineId = newMedicine.Id,
                    IngredientId = newMedicine.ActiveSubstanceId,
                    Ratio = 1,
                });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.CategoryId = new SelectList(_context.Categories, "Id", "Name", medicine.CategoryId);
            ViewBag.ActiveSubstanceId = new SelectList(_context.Ingredients, "Id", "Name", medicine.ActiveSubstanceId);
            ViewBag.FactoryId = new SelectList(_context.Factories, "Id", "Name", medicine.FactoryId);

            return View(medicine);
        }



        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Medicines == null)
            {
                return NotFound();
            }

            var medicine = await _context.Medicines.FindAsync(id);
            if (medicine == null)
            {
                return NotFound();
            }

            ViewBag.CategoryId = new SelectList(_context.Categories, "Id", "Name");
            ViewBag.ActiveSubstanceId = new SelectList(_context.Ingredients, "Id", "Name");
            ViewBag.FactoryId = new SelectList(_context.Factories, "Id", "Name");
            return View(medicine);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute]int id, [Bind("Name, Description, CategoryId, Dose, ActiveSubstanceId, InStock, FactoryId, TradeName")] EditMedicineRequest medicine)
        {



            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(new Medicine()
                    {
                        Id = id,
                        Name = medicine.Name,
                        Description = medicine.Description,
                        CategoryId = medicine.CategoryId,
                        Dose = medicine.Dose,
                        ActiveSubstanceId = medicine.ActiveSubstanceId,
                        InStock = medicine.InStock,
                        FactoryId = medicine.FactoryId,
                        TradeName  = medicine.TradeName,
                    });
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                    throw;

                }
                return RedirectToAction(nameof(Index));
            }


            ViewBag.CategoryId = new SelectList(_context.Categories, "Id", "Name", medicine.CategoryId);
            ViewBag.ActiveSubstanceId = new SelectList(_context.Ingredients, "Id", "Name", medicine.ActiveSubstanceId);
            ViewBag.FactoryId = new SelectList(_context.Factories, "Id", "Name", medicine.FactoryId);
            return View(medicine);
        }
        public async Task<IActionResult> EditIngredients(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            Medicine? medicine = await _context.Medicines.FindAsync(id);
            if (medicine is null)
            {
                return NotFound();
            }
            var filteredIngredients =  _context.MedicineIngredients
                                    .Where(i => i.MedicineId == id)
                                    .Include(e => e.Ingredient)
                                    .ToList();

            var ingredients = new VWModels.MedicineIngredient.ShowIngredientsResponse();
            
            ingredients.MedicineId = (int)id;
            ingredients.Ingredients = filteredIngredients.Select(i => new IngredientInfo()
            {
                Id = i.Ingredient.Id,
                Name = i.Ingredient.Name,
                Ratio = i.Ratio
            }).ToList();

            ViewBag.FilteredIngredients = new SelectList(filteredIngredients, "Id", "Name");
            ViewBag.Ingredients = new SelectList(_context.Ingredients, "Id", "Name");

            return View(ingredients);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddIngredient([FromRoute]int id,[Bind("IngredientId","Ratio")] AddIngredientToMedicineRequest ingredientToMedicine)
        {

            if (ModelState.IsValid)
            {
                _context.Add(new MedicineIngredient()
                {
                    IngredientId = ingredientToMedicine.IngredientId,
                    MedicineId = id,
                    Ratio = ingredientToMedicine.Ratio,
                });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(EditIngredients), new { id = id });
            }

            return RedirectToAction(nameof(EditIngredients), new { id = id });

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteIngredient( int ingredientId,  int medicineId)
        {

            if (ModelState.IsValid)
            {
                var MedicineIngredient = await _context.MedicineIngredients
                            .FirstOrDefaultAsync(m => m.MedicineId == medicineId && m.IngredientId == ingredientId);
                if (MedicineIngredient  is not null)
                {
                    _context.MedicineIngredients.Remove(MedicineIngredient);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(EditIngredients), new { id = medicineId });
            }

            return RedirectToAction(nameof(EditIngredients), new { id = medicineId });

        }
        public async Task<IActionResult> EditIngredient(int ingredientId, int medicineId)
        {
            var ingredient =  _context.MedicineIngredients
                                    .Where(m => m.IngredientId == ingredientId && m.MedicineId == medicineId)
                                    .Include(e => e.Ingredient)
                                    .Select(i => new EditIngredientInMedicineRequest()
                                    {
                                        MedicineIngredientId = i.Id,
                                        MedicineId = i.MedicineId,
                                        Ingredient=new IngredientInfo()
                                        {
                                            Id = i.Ingredient.Id,
                                            Name = i.Ingredient.Name,
                                            Ratio = i.Ratio
                                        },
                                    }).ToList();

        
            if (ingredient == null)
            {
                return NotFound();
            }

            

            return View(ingredient[0]);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditIngredient(EditIngredientInMedicineRequest model)
        {

            if (ModelState.IsValid)
            {

                var medicineIngredient = new MedicineIngredient
                {
                    Id = model.MedicineIngredientId,
                    MedicineId = model.MedicineId,
                    IngredientId = model.Ingredient.Id,
                    Ratio = model.Ingredient.Ratio
                };
                if (medicineIngredient is not null)
                {
                    _context.Update(medicineIngredient);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(EditIngredients), new { id = model.MedicineId });
            }

WebTest/Views/Factories/Create.cshtml
@model DataAccess.Models.Factory

@{
    ViewData["Title"] = "Create Category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="display-4">Create Factory</h1>
            <p class="lead">Fill in the details below to add a new factory.</p>
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group mt-3">
                            <input type="submit" value="Create" class="btn btn-primary" />
                            <a asp-action="Index" class="btn btn-secondary ms-2">Back to List</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebTest/Views/Factories/Delete.cshtml
@model DataAccess.Models.Factory

@{
    ViewData["Title"] = "Delete Factory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="display-4">Delete Factory</h1>
            <p class="lead">Are you sure you want to delete this Factory?</p>
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <div>
                        <h4>Factory</h4>
                        <hr />
                        <dl class="row">
                            <dt class="col-sm-3">
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>
                            <dd class="col-sm-9">
                                @Html.DisplayFor(model => model.Name)
                            </dd>
                        </dl>
                    </div>
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group mt-3">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                            <a asp-action="Index" class="btn btn-secondary ms-2">Back to List</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WebTest/Views/Factories/Details.cshtml
@model WebTest.VWModels.Factory.ShowMedicinesResponse

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="display-4">Factory Details</h1>
            <hr />
            <div class="row">
                <div class="col-md-12">
                    <dl class="row">
                        <dt class="col-sm-3">Name:</dt>
                        <dd class="col-sm-9">@Html.DisplayFor(model => model.Name)</dd>
                    </dl>
                    <table class="table table-hover table-striped mt-4">
                        <thead class="thead-dark">
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Medicines.First().Name)</th>
                                <th>@Html.DisplayNameFor(model => model.Medicines.First().TradeName)</th>
                                <th>@Html.DisplayNameFor(model => model.Medicines.First().Dose)</th>
                                <th>@Html.DisplayNameFor(model => model.Medicines.First().InStock)</th>
                                <th>@Html.DisplayNameFor(model => model.Medicines.First().Category)</th>
                                <th>@Html.DisplayNameFor(model => model.Medicines.First().ActiveSubstance)</th>
                                <th class="text-end">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Medicines)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.TradeName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Dose)</td>
                                    <td>@Html.DisplayFor(modelItem => item.InStock)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Category)</td>
                                    <td>@Html.DisplayFor(modelItem => item.ActiveSubstance)</td>
                                    <td class="text-end">
                                        <a class="btn btn-info btn-sm" asp-controller="Medicines" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                        <a class="btn btn-secondary btn-sm" asp-controller="Medicines" asp-action="Details" asp-route-id="@item.Id">Details</a>
                                        <a class="btn btn-danger btn-sm" asp-controller="Medicines" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div class="mt-3">
                        <a asp-action="Edit" asp-route-id="@Model?.FactoryId" class="btn btn-primary">Edit</a>
                        <a asp-action="Index" class="btn btn-secondary ms-2">Back to List</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebTest/Views/Factories/Edit.cshtml
@model WebTest.VWModels.Factory.EditFactoryRequest

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="display-4">Edit Factory</h1>
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group mt-3">
                            <input type="submit" value="Save" class="btn btn-primary" />
                            <a asp-action="Index" class="btn btn-secondary ms-2">Back to List</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebTest/Views/Factories/Index.cshtml
@model IEnumerable<DataAccess.Models.Factory>

@{
    ViewData["Title"] = "Factories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="display-4">Factories</h1>
            <p class="lead">
                Manage your factories below or <a class="btn btn-primary" asp-action="Create">Create New</a>
            </p>
            <table class="table table-hover table-striped mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th class="text-end">Actions</th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td class="text-end">
                            <a class="btn btn-info btn-sm" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <a class="btn btn-secondary btn-sm" asp-action="Details" asp-route-id="@item.Id">Details</a>
                            <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
}