WebTest/Controllers/DescriptionsController.cs
using Microsoft.AspNetCore.Mvc;
using DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using WebTest.VWModels.Description;
using Microsoft.AspNetCore.Mvc.Rendering;
namespace WebTest.Controllers
{
    public class DescriptionsController : BaseController
    {
        public DescriptionsController(PharmacyContext context) : base(context)
        {
        }
        override
        public async Task<IActionResult> Index()
        {
            return _context.Descriptions != null ?
                View(await _context.Descriptions
                .Include(d => d.Patient)
                .ToListAsync()) :
                Problem("Entity set 'PharmacyContext.Descriptions'  is null.");
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromRoute]int id, [Bind("Name", "Description1")] CreateDescriptionRequest description)
        {
            if (ModelState.IsValid)
            {
                _context.Add(new Description()
                {
                    Name = description.Name,
                    PatientId = id,
                    Description1 = description.Description1,
                });
                await _context.SaveChangesAsync();
                return RedirectToAction("Details" , "Patients",new {id = id});
            }
            return View(description);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var description = await _context.Descriptions.FindAsync(id);
            if (description is null)
            {
                return NotFound();
            }
            var descriptionModel = new EditDescriptionRequest()
            {
                Id = (int)id,
                Name = description.Name,
                Description1 = description.Description1,
                PatientId = description.PatientId,
            };

            return View(descriptionModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,[Bind("Name", "PatientId", "Description1")] EditDescriptionRequest description)
        {
            if (ModelState.IsValid)
            {
                _context.Update(new Description()
                {
                    Id = id,
                    Name = description.Name,
                    PatientId = description.PatientId,
                    Description1 = description.Description1,
                });
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Patients", new { id = description.PatientId });
            }
            return View(description);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var description = await _context.Descriptions
                            .Include(i=>i.Patient)
                            .FirstOrDefaultAsync(i => i.Id == id);
            if (description is null)
            {
                return NotFound();
            }
            var filteredMedicines = _context.DescriptionMedicines
                                    .Where(i => i.DescriptionId == id)
                                    .Include(e => e.Medicine)
                                    .Include(e => e.Medicine.Factory)
                                    .Include(e => e.Medicine.Category)
                                    .Include(e => e.Medicine.ActiveSubstance)

                                    .ToList();

            var medicines = new VWModels.Description.ShowMedicinesResponse();

            medicines.DescriptionId = (int)id;
            medicines.Name = description.Name;
            medicines.Description1 = description.Description1;
            medicines.Medicines = filteredMedicines
                                    .Select(i => new MedicineInfo()
                                    {
                                        Id = i.Id,
                                        Name = i.Medicine.Name,
                                        TradeName = i.Medicine.TradeName,
                                        InStock = i.Medicine.InStock,
                                        Dose = i.Medicine.Dose,
                                        Factory = i.Medicine.Factory.Name,
                                        Count = i.Count,
                                    }).ToList();

            ViewBag.Description = description;
            return View(medicines);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var description = await _context.Descriptions
                            .Include(i => i.Patient)
                            .FirstOrDefaultAsync(i => i.Id == id);
            if (description is null)
            {
                return NotFound();
            }

            return View(description);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            if (_context.Descriptions is null)
            {
                return Problem("Entity set 'PharmacyContext.Descriptions  is null.");
            }
            var description = await _context.Descriptions
                            .Include(i => i.Patient)
                            .FirstOrDefaultAsync(i => i.Id == id);
            if (description is not null)
            {
                _context.Descriptions.Remove(description);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> EditMedicines(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            Description? description = await _context.Descriptions.FindAsync(id);
            if (description is null)
            {
                return NotFound();
            }
            var filteredMedicines = _context.DescriptionMedicines
                                    .Where(i => i.DescriptionId == id)
                                    .Include(e => e.Medicine)
                                    .Include(e=>e.Medicine.Factory)
                                    .ToList();

            var medicines = new VWModels.DescriptionMedicine.ShowMedicinesResponse();

            medicines.DescriptionId = (int)id;
            medicines.Medicines = filteredMedicines.Select(i => new VWModels.Description.MedicineInfo()
            {
                Id = i.Medicine.Id,
                Name = i.Medicine.Name,
                Dose = i.Medicine.Dose,
                TradeName = i.Medicine.TradeName,
                Count = i.Count,
                Factory = i.Medicine.Factory.Name,
                InStock = i.Medicine.InStock,
            }).ToList();
            ViewBag.Medicines = new SelectList(_context.Medicines, "Id", "Name");

            return View(medicines);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMedicine([FromRoute] int id, [Bind("MedicineId", "Count")] VWModels.DescriptionMedicine.AddMedicineToDescriptionRequest medicine )
        {

            if (ModelState.IsValid)
            {
                _context.Add(new DescriptionMedicine()
                {
                    DescriptionId = id,
                    MedicineId = medicine.MedicineId,
                    Count = medicine.Count,
                });

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(EditMedicines), new { id = id });
            }
            return RedirectToAction(nameof(EditMedicines), new { id = id });

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteMedicine(int medicineId, int descriptionId)
        {

            if (ModelState.IsValid)
            {
                var descriptionmedicine = await _context.DescriptionMedicines
                            .FirstOrDefaultAsync(m => m.MedicineId == medicineId && m.DescriptionId == descriptionId);
                if (descriptionmedicine is not null)
                {
                    _context.DescriptionMedicines.Remove(descriptionmedicine);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(EditMedicines), new { id = descriptionId });
            }

            return RedirectToAction(nameof(EditMedicines), new { id = descriptionId });

        }
        public async Task<IActionResult> EditMedicine(int medicineId, int descriptionId)
        {
            var descriptionmedicine = await _context.DescriptionMedicines
                                    .Where(m => m.MedicineId == medicineId && m.DescriptionId == descriptionId)
                                    .Select(i => new VWModels.DescriptionMedicine.EditMedicineinDescriptionRequest()
                                    {
                                        DescriptionMedicineId = i.Id,
                                        DescriptionId = descriptionId,
                                        MedicineId = medicineId,
                                        Medicine = new VWModels.DescriptionMedicine.MedicineInfo()
                                        {
                                            Count = i.Count,
                                            
                                        }
                                    }).ToListAsync();

            Console.WriteLine(descriptionmedicine.Count);

WebTest/Views/Descriptions/Create.cshtml
@model WebTest.VWModels.Description.CreateDescriptionRequest

@{
    ViewData["Title"] = "Create Description";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="display-4">Create Description</h1>
            <p class="lead">Fill in the details below to add a new description.</p>
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description1" class="control-label"></label>
                            <textarea asp-for="Description1" class="form-control"></textarea>
                            <span asp-validation-for="Description1" class="text-danger"></span>
                        </div>
                        <div class="form-group mt-3">
                            <input type="submit" value="Create" class="btn btn-primary" />
                            <a asp-action="Index" class="btn btn-secondary ms-2">Back to List</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebTest/Views/Descriptions/Delete.cshtml
@model DataAccess.Models.Description

@{
    ViewData["Title"] = "Delete Description";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="display-4">Delete Description</h1>
            <p class="lead">Are you sure you want to delete this Description?</p>
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <div>
                        <h4>Description</h4>
                        <hr />
                        <dl class="row">
                            <dt class="col-sm-3">Name:</dt>
                            <dd class="col-sm-9">@Html.DisplayFor(model => model.Name)</dd>
                            <dt class="col-sm-3">Description:</dt>
                            <dd class="col-sm-9">@Html.DisplayFor(model => model.Description1)</dd>
                            <dt class="col-sm-3">Patient:</dt>
                            <dd class="col-sm-9">@Html.DisplayFor(model => model.Patient.FirstName)</dd>
                        </dl>
                    </div>
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group mt-3">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                            <a asp-action="Index" class="btn btn-secondary ms-2">Back to List</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WebTest/Views/Descriptions/Details.cshtml
@model WebTest.VWModels.Description.ShowMedicinesResponse

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="display-4">Description Details</h1>
            <hr />
            <div class="row">
                <div class="col-md-12">
                    <dl class="row">
                        <dt class="col-sm-3">Name:</dt>
                        <dd class="col-sm-9">@Html.DisplayFor(model => model.Name)</dd>
                        <dt class="col-sm-3">Description:</dt>
                        <dd class="col-sm-9">@Html.DisplayFor(model => model.Description1)</dd>
                        <dt class="col-sm-3">Patient:</dt>
                        <dd class="col-sm-9">@ViewBag.Description.Patient.FirstName</dd>
                    </dl>
                    <hr />
                    <h1>Medicines</h1>
                    <table class="table table-hover table-striped mt-4">
                        <thead class="thead-dark">
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Medicines.First().Name)</th>
                                <th>@Html.DisplayNameFor(model => model.Medicines.First().TradeName)</th>
                                <th>@Html.DisplayNameFor(model => model.Medicines.First().Dose)</th>
                                <th>@Html.DisplayNameFor(model => model.Medicines.First().InStock)</th>
                                <th>@Html.DisplayNameFor(model => model.Medicines.First().Factory)</th>
                                <th>@Html.DisplayNameFor(model => model.Medicines.First().Count)</th>
                                <th class="text-end">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Medicines)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.TradeName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Dose)</td>
                                    <td>@Html.DisplayFor(modelItem => item.InStock)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Factory)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Count)</td>
                                    <td class="text-end">
                                        <a class="btn btn-info btn-sm" asp-controller="Medicines" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                        <a class="btn btn-secondary btn-sm" asp-controller="Medicines" asp-action="Details" asp-route-id="@item.Id">Details</a>
                                        <a class="btn btn-danger btn-sm" asp-controller="Medicines" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div class="mt-3">
                        <a asp-action="Edit" asp-route-id="@Model?.DescriptionId" class="btn btn-primary">Edit</a>
                        <a href="@Url.Action("EditMedicines", "Descriptions", new { id = Model.DescriptionId })" class="btn btn-primary  ms-2">Edit Medicines</a>
                        <a asp-action="Index" class="btn btn-secondary ms-2">Back to List</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebTest/Views/Descriptions/Edit.cshtml
@model WebTest.VWModels.Description.EditDescriptionRequest

@{
    ViewData["Title"] = "Edit Description";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="display-4">Edit Description</h1>
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description1" class="control-label"></label>
                            <textarea asp-for="Description1" class="form-control"></textarea>
                            <span asp-validation-for="Description1" class="text-danger"></span>
                            <input type="hidden" value="@Model.PatientId" asp-for="PatientId" />
                        </div>
                        <div class="form-group mt-3">
                            <input type="submit" value="Edit" class="btn btn-primary" />
                            <a href="@Url.Action("EditMedicines", "Descriptions", new { id = Model.Id })" class="btn btn-primary  ms-2">Edit Medicines</a>
                            <a asp-action="Index" class="btn btn-secondary ms-2">Back to List</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebTest/Views/Descriptions/EditMedicine.cshtml
@model WebTest.VWModels.DescriptionMedicine.EditMedicineinDescriptionRequest

@{
    ViewData["Title"] = "Edit Medicine";
}

<h1>Edit Medicine</h1>

<form asp-action="EditMedicine" method="post">
    <div class="col-md-6">
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.MedicineId):
            </dt>
            <dd class="col-sm-2">
                @Html.DisplayFor(model => model.MedicineId)
            </dd>
        </dl>
        <div class="form-group">
            <label asp-for="Medicine.Count">Count:</label>
            <input asp-for="Medicine.Count" class="form-control" />
            <span asp-validation-for="Medicine.Count" class="text-danger"></span>
            <input type="hidden" value="@Model.MedicineId" asp-for="Medicine.Id" />

        </div>
        <input type="hidden" value="@Model.MedicineId" asp-for="MedicineId" />
        <input type="hidden" value="@Model.DescriptionId" asp-for="DescriptionId" />
        <input type="hidden" value="@Model.DescriptionMedicineId" asp-for="DescriptionMedicineId" />
        <div class="form-group mt-4">
            <button type="submit" class="btn btn-primary">Edit Medicine</button>
            <a asp-action="EditMedicines" asp-route-id="@Model.DescriptionId" class="btn btn-secondary ms-2">Back</a>
        </div>
    </div>
</form>


@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

WebTest/Views/Descriptions/EditMedicines.cshtml
@model WebTest.VWModels.DescriptionMedicine.ShowMedicinesResponse


<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">

            <h1>Medicines</h1>

            <table class="table table-hover table-striped mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th>Name</th>
                        <th>TradeName</th>
                        <th>Count</th>
                        <th>InStock</th>
                        <th>Dose</th>
                        <th>Factory</th>
                        <th class="text-end">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var medicine in Model.Medicines)
                    {
                        <tr>
                            <td>@medicine.Name</td>
                            <td>@medicine.TradeName</td>
                            <td>@medicine.Count</td>
                            <td>@medicine.InStock</td>
                            <td>@medicine.Dose</td>
                            <td>@medicine.Factory</td>
                            <td class="text-end">
                                <a class="btn btn-info btn-sm" asp-action="EditMedicine" asp-controller="Descriptions" asp-route-medicineId="@medicine.Id" asp-route-descriptionId="@Model.DescriptionId">Edit</a>
                                <form asp-controller="Descriptions" asp-action="DeleteMedicine" method="post" style="display:inline;">
                                    <input type="hidden" name="medicineId" value="@medicine.Id" />
                                    <input type="hidden" name="descriptionId" value="@Model.DescriptionId" />
                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            <div class="row">
                <div class="col-md-6">
                    <h4>Add New Medicine</h4>
                    @using (Html.BeginForm("AddMedicine", "Descriptions", new { id = Model.DescriptionId }, FormMethod.Post))
                    {

                        <form asp-action="AddMedicine" asp-controller="Descriptions" method="post">
                            <div class="form-group">
                                <label for="MedicineId">Medicine:</label>
                                <select id="MedicineId" name="MedicineId" class="form-control" asp-items="@ViewBag.Medicines"></select>
                            </div>
                            <div class="form-group">
                                <label for="Count">Count:</label>
                                <input type="text" id="Count" name="Count" class="form-control" />
                            </div>
                            <div class="form-group mt-4">
                                <input type="submit" value="Add Medicine" class="btn btn-primary" />
                                <a asp-action="Index" class="btn btn-secondary ms-2">Back to List</a>
                            </div>
                        </form>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

WebTest/Views/Descriptions/Index.cshtml
@model IEnumerable<DataAccess.Models.Description> 

@{
    ViewData["Title"] = "Descriptions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="display-4">Descriptions</h1>
            <p class="lead">List of all descriptions.</p>
            <hr />
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th class="text-end">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Description1</td>
                            <td class="text-end">
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info btn-sm">Edit</a>
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary btn-sm">Details</a>
                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>